version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: mkschallenge-app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    depends_on:
      - postgresdb
      - redisdb

  postgresdb:
    build: .docker/postgres
    container_name: mkschallenge-postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mkschallenge
  redisdb:
    build: .docker/redis
    container_name: mkschallenge-redis
    restart: always
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - .docker/dbdata:/var/lib/redis
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      